### ISSUE TITLE
* Priority: Add editable Preview icon+modal for seeing the rest of the content

### ISSUE THREAD

**Issue by arapawa** [dannytpeck/calendar-builder-client#1]
Moving this from the other repo https://github.com/dannytpeck/calendar-builder/

Opens modal or something showing:
* image
* title
* short + long description

Probably use Dengue as an example.

For AM:
Editable preview.

For Client:
Editable.

Must use a WYSIWYG editor, probably Trumbowyg.

- [x] Figure out an icon to use.
   Forget it, let's just use the edit icon we have.
- [x] Design the view/modal/whatever the preview will live in

**Comment by arapawa** [comment]
@dannytpeck Here are the mockups for the Edit Challenge modal. I made a few different versions based on the config options selected (e.g., Individual vs. Team).
![edit challenge modal one time](https://user-images.githubusercontent.com/16523445/41995428-939a1b74-7a06-11e8-9e9c-307b84c278a3.png)
![edit challenge modal verified](https://user-images.githubusercontent.com/16523445/41995429-93bc32c2-7a06-11e8-9b3e-92805f53a851.png)
![edit challenge modal one time units - team](https://user-images.githubusercontent.com/16523445/41995430-93e1ed96-7a06-11e8-9df5-01bf3820be20.png)
![edit challenge modal weekly](https://user-images.githubusercontent.com/16523445/41995431-940a4912-7a06-11e8-8d50-48d40c8210b7.png)

**Comment by arapawa** [comment]
Let's see if there's a good React alternative to Trumbowyg, for ease and pleasantness of coding.

**Comment by dannytpeck** [comment]
Welcome to the largest feature we were working on here that required updating the DB and the code in a craaaazy amount of places and probably still more I haven't found yet 🗡 😆 

35f25ed7

**Comment by arapawa** [comment]
@dannytpeck Dude you're a trooper and rocked this update.
