### ISSUE TITLE
Add "Ghost Text" for CIEs

### ISSUE THREAD

**Issue by arapawa** [dannytpeck/calendar-builder-client#14]
Leadership wants the standard description text included in the edit modal when you click on WBA for instance. But it should be locked down and greyed out. The only thing you should be able to edit is the points!

- [ ] @dannytpeck  Pull in CIE text and images to CIE tile previews, but make fields readonly/disabled
- [x] @dannytpeck Add text into Airtable Templates (receiving text from Jill)
- [x] @arapawa Add images into Airtable Templates

**Comment by dannytpeck** [comment]
@arapawa Made instructions and long desc readonly tied to an 'editable' variable.
we could do any field we want easily enough, but these are the only ones I remember Jill mentioning explicitly!

51d820a
