### ISSUE TITLE
Create 'print' view

### ISSUE THREAD

**Issue by arapawa** [dannytpeck/calendar-builder-client#3]
For when clients want to print out the calendar.
Print styles that show all content opened.

Add print button if possible (can just call the window.print() command)

**Comment by arapawa** [comment]
Try overriding accordion to allow opening all accordions at once.

**Comment by arapawa** [comment]
Mostly resolved with https://github.com/dannytpeck/calendar-builder-client/pull/10 which allows all cards to be opened simultaneously.
Users can then do the standard page printing methods of Ctrl+P or File->Print.

Leaving this as open for now until the PR is merged and hosted.

**Comment by dannytpeck** [comment]
9419c1fd

**Comment by dannytpeck** [comment]
🖨
