### ISSUE TITLE
Move the link/share button to the Client Calendars view

### ISSUE THREAD

**Issue by arapawa** [dannytpeck/calendar-builder-client#4]
Put the icon between the Edit and Airplane icons.

This will move this feature from -client to https://github.com/dannytpeck/calendar-builder

**Comment by dannytpeck** [comment]
@arapawa I removed it from this app, but I think we'll need an issue and a good run down of how we want this look! I'd wing it, buuuuut

**Comment by dannytpeck** [comment]
@arapawa Gonna close this out so we look good
