### ISSUE TITLE
Add Percentages to bottom view

### ISSUE THREAD

**Issue by arapawa** [dannytpeck/calendar-builder-client#7]
For 25%, 50%, 75% of completing the Challenges.
Those percentages of points total.

- [x] @arapawa Design/Redline where it will go on the page
- [ ] @dannytpeck Program in regex formula and stuff to populate values into view

**Comment by arapawa** [comment]
@dannytpeck These chumps will go underneath the accordion, right-aligned.

![point_counts](https://user-images.githubusercontent.com/16523445/42661632-a5e07b46-85e3-11e8-8306-be15baa9621d.png)

**Comment by arapawa** [comment]
@arapawa Design with border around Point Totals percentages.

**Comment by arapawa** [comment]
Here it is with borders around the percentages.
![cb-new-withboxes-mock](https://user-images.githubusercontent.com/16523445/43105190-e1710b0a-8e88-11e8-8e68-33aa068b30be.png)

I vote to use the other one instead. #noborders

**Comment by dannytpeck** [comment]
Aaaaaaall set f671eed5
