### ISSUE TITLE
Add count of each HP category

### ISSUE THREAD

**Issue by arapawa** [dannytpeck/calendar-builder-client#8]
- [x] @arapawa Design where it will go on the page (potentially at the top?)
- [ ] @dannytpeck  Add the icons and counts of each to the Edit Calendar view

**Comment by arapawa** [comment]
@dannytpeck These suckas will go above the accordion, right-aligned.
![hp_counts](https://user-images.githubusercontent.com/16523445/42661184-44a005f0-85e2-11e8-89f1-02ec0de87fb3.png)

**Comment by dannytpeck** [comment]
e22705be

**Comment by dannytpeck** [comment]
SCHWING
