### ISSUE TITLE
* Priority: Add 'Approve' button for clients to approve the calendar

### ISSUE THREAD

**Issue by arapawa** [dannytpeck/calendar-builder-client#9]
In order for clients to approve the calendar and have the status change from 'In Progress' to 'ready to load' or whatever it's called.

Button will live on the bottom of the page, in the center, like this:
![approve-button](https://user-images.githubusercontent.com/16523445/42066491-96143570-7af5-11e8-9ce0-43cf04beb72a.png)

When clicked, confirmation modal will appear, like this:
![confirm-calendar](https://user-images.githubusercontent.com/16523445/42066498-a005f654-7af5-11e8-8c11-b9059fa467bb.png)

When approved, modal will have message like this (only, not redundant):
![ready-to-load](https://user-images.githubusercontent.com/16523445/42066502-a54a865c-7af5-11e8-9062-9bbc17b37a95.png)

**Comment by arapawa** [comment]
@dannytpeck 
![view calendar client - start](https://user-images.githubusercontent.com/16523445/42653201-9a6e3704-85c9-11e8-9083-c3768a1c6c18.png)

Here it is in context on the page, as well as the 'Done' button. The 'Done' button could also be the Cancel link, Back button, or whatever. It would just close the browser tab (which totally makes sense since for clients all they see is that tab, and AMs would still have the tab for cb-admin).

![close-the-tab](https://user-images.githubusercontent.com/16523445/42653238-bc0b6d50-85c9-11e8-8857-56848247b4bb.jpg)

Or, I guess, we could just have the 'Accept' button. Who knows. Follow your heart.

**Comment by dannytpeck** [comment]
3e2b1c2e
